version: "3.1"


services:
  
  db:
    image: mysql/mysql-server
    command: --skip-host-cache
    restart: always
    container_name: db
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=nest
    volumes:
      - ./my-db:/var/lib/mysql
    
  web:
    build : ./FRONT
  

  api:
    build : ./BACK
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080

  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
        - 15672:15672

#  maildevt3:
#        container_name: maildevt3
#        image: djfarrelly/maildev
#        ports:
#            - 8003:80
  
  quarkus:
    build: 
      context: ./Quarkus
      dockerfile : src/main/docker/Dockerfile.native


    depends_on:
      - rabbitmq
  
  nginx:
    image: nginx:latest
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
