version: "3.1"


services:
  
  db:
    image: mysql/mysql-server
    command: --skip-host-cache
    restart: always
    container_name: db
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=nest
    volumes:
      - ./my-db:/var/lib/mysql
    
  web:
    build :
      context: ./FRONT
      dockerfile: Prod_dockerfile
  

  api:
    build : ./BACK
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080

  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
        - 15672:15672

#  maildevt3:
#        container_name: maildevt3
#        image: djfarrelly/maildev
#        ports:
#            - 8003:80
  
  quarkus:
    build: 
      context: ./Quarkus
      dockerfile : src/main/docker/Dockerfile.native


    depends_on:
      - rabbitmq
  
  nginx:
    image: nginx:latest
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
  
  prometheus:
    image: prom/prometheus
    depends_on:
      - api
      - quarkus
      - rabbitmq
    volumes:
      - prometheus-data:/prometheus
      - ./Monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3001
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - ./Monitoring/grafana/grafanaDashboard.yaml:/etc/grafana/dashboards/grafanaDashboard.yaml
      - ./Monitoring/grafana/grafanaDatasource.yaml:/etc/grafana/provisioning/datasources/grafanaDatasource.yaml

volumes:
  grafana-data: 
  grafana-config: 
  grafana-dashboards: 
  prometheus-data:
